steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/dev-staging-337304/wordpress-container/wordpress:$SHORT_SHA', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/dev-staging-337304/wordpress-container/wordpress:$SHORT_SHA' ]

- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'
  args:
  - 'apply'
  - '-f'
  - 'k8s/'

- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'
  args:
  - 'set'
  - 'image'
  - 'deployment/wordpress'
  - '-n wordpress'
  - 'wordpress=us-central1-docker.pkg.dev/dev-staging-337304/wordpress-container/wordpress:$SHORT_SHA'

images:
- 'us-central1-docker.pkg.dev/dev-staging-337304/wordpress-container/wordpress:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
