apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: wordpress
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ= # base64 for 'password'
  mysql-wpuser-password: cGFzc3dvcmQ= # base64 for 'password' 
